Logging:
    LogLevel:
        Default: Debug
        Microsoft.AspNetCore: Warning
AllowedHosts: "*"
Jwt:
    Issuer: CHANGE_ISSUER
    Audience:  CHANGE_AUDIENCE
    Key: CHANGE_KEY_0123456789012345678901234567890123456789
    AesKey: JnKmNZBsKlrTlhDypPmcIVLM8Sgcw5Z349xue21+GNw=
    AesIv: 64x6MU/o0UAVkQyfk54vlA==